name: repository
on:
  repository_dispatch:
    types: [my-event]

jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      # - name: Determine Branch Name
      #   uses: haya14busa/action-cond@v1
      #   id: fetchBranch
      #   with:
      #     cond: ${{ github.event.client_payload.ref }}
      #     if_true: ${{ github.event.client_payload.ref }}
      #     if_false: 'develop'
      # - name: Repo Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     ref: ${{ steps.fetchBranch.outputs.value }}

      - name: Repo Checkout
        uses: actions/checkout@v3
        # run: |
        #  git checkout $(git show-branch ${{ github.event.client_payload.ref }} &>/dev/null && echo ${{ github.event.client_payload.ref }} || echo develop)
      - run: echo "SUCCESS FULL MASTER"
      - run: echo ${{ github.event.client_payload.sha }}
      - run: echo ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.url }}

# Find that the checkout of ref branch 