name: workflow

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Pause for 25 seconds
        run: |
          echo "SUCCESS"
          echo ${{ github.event.client_payload.sha }}
          echo ${{ github.event.client_payload.ref }}
          echo ${{ github.event.client_payload.url }}
          sleep 25